### ISSUE TITLE
Add ability to exit program

### ISSUE THREAD

**Issue by oabdulmatin** [mcmonkeyprojects/KeyboardChatterBlocker#10]
As far as I know the only way to close the Keyboard Chatter Blocker right now is to kill it through the Task Manager.  Please add the ability to exit the program. 

A few thoughts:
_Repurpose close window button (X in topright) in program to exit Keyboard Chatter Blocker_
* Clicking the X icon displays a confirmation modal (Are you sure you want to exit? Yes/No) 
* With this change, it would probably make sense to also repurpose the minimize icon (-) to minimize the program to tray (currently functionality of the X button)

_Add context menu option to tray icon to close program_
![image](https://user-images.githubusercontent.com/69395885/94089609-97889100-fde1-11ea-8aa4-bb227c3f5977.png)

**Comment by mcmonkey4eva** [comment]
The "Start In Tray" checkbox causes the close button to close the window but leave the program running in tray. To make it close entirely, just uncheck "Start In Tray", at which point pressing the close button will entirely stop the program.
