### ISSUE TITLE
Feature request: disable when certain applications are open

### ISSUE THREAD

**Issue by conflitz** [mcmonkeyprojects/KeyboardChatterBlocker#11]
The application generally works great, but it can introduce issues with certain programs. For example, chatter while playing a game can result in not being able to press down a key momentarily. 

My suggestion is to add a way to disable the chatter blocker when certain applications are open or in focus. The user could choose which applications disable the blocker. The current but less elegant solution of disabling the blocker manually works, but it would be simpler if this could be done automatically.

**Comment by mcmonkey4eva** [comment]
That's definitely a good feature to add.

I've added that functionality and an interface for it (via the commits listed above), and have published it in [Release 1.07](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases) and higher (including 1.08, which I've immediately published to fix a mistake in the interface's formatting).

It works based on process name (aka the executable file name minus the `.exe` part - so like `firefox`, `chrome`, etc) and will automatically disable the blocker when a process with a listed named is running (currently checks every ~2 seconds, as that seemed like a good balance between activating rapidly, but still avoiding any noticeable CPU usage), and will automatically re-enable when there's no such processes listed.

The interface lets you quickly add or remove by name, including the ability to select a program already in the list to remove it more easily, or select a program from the set of all current open processes (with the `(...)` button) to add. It will highlight programs that are currently open (and thus causing an automatic disable) in red.

![screenshot](https://i.alexgoodwin.media/i/misc/a10951.png)

Hope this meets your needs!
