### ISSUE TITLE
Submit  Program  to Chocolatey

### ISSUE THREAD

**Issue by jens1101** [mcmonkeyprojects/KeyboardChatterBlocker#13]
It would be very useful if this program could be submitted to [Chocolatey](https://chocolatey.org/packages/) as a package. This would allow me to install it quickly via a command.

**Comment by mcmonkey4eva** [comment]
Sorry for the delay here,

I've never used Chocolatey before, but I've submitted KeyboardChatterBlocker v1.08 there. It's listed @ https://community.chocolatey.org/packages/keyboardchatterblocker

Chocolatey apparently has manual human review of all new submissions, so it will be "a couple business days" before it's accepted, but when it is that will allow the following steps:
- `choco install keyboardchatterblocker` to install it
- `keyboardchatterblocker.exe` (or just like, `keyboard` then hit tab or something) to open the control form and operate as normal as described in the readme.

**Comment by jens1101** [comment]
@mcmonkey4eva Thank you for putting the app on Chocolatey. I was able to install the current version and it works well.

Thank you for your efforts!
