### ISSUE TITLE
PSA: Don't run this application while playing games using VAC

### ISSUE THREAD

**Issue by brajevicm** [mcmonkeyprojects/KeyboardChatterBlocker#15]
As title says, bear in mind that running this application will get you VAC banned while playing games such as CSGO.

**Comment by mcmonkey4eva** [comment]
That's unfortunate, but makes sense how that'd happen - I guess the anticheat detects that you have software that's altering keystrokes, and doesn't really look deeper into what alterations are being done, just bans right away to be safe.

I added a note to the readme including a link to this issue to hopefully be seen by any new users that play CSGO or other online games with that type of aggressive anticheat.

**Comment by ruzrobert** [comment]
Hi! Is it enough to use the "Auto Disable Programs" / "Auto Disable If Any Fullscreen" to avoid bans in games, or it is better to fully exit the app? @mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
@ruzrobert That's more a question for anticheat developers than for me, but - the autodisable will unregister the keyboard hook, so it _should_ be considered safe, but I can't make promises - anticheats tend to overreact sometimes.
