### ISSUE TITLE
Add date in the log

### ISSUE THREAD

**Issue by Suddow** [mcmonkeyprojects/KeyboardChatterBlocker#16]
Would it be possible to add the shortform date (like "6/29") in the log timestamp?

**Comment by mcmonkey4eva** [comment]
I hadn't actually given thought to the fact that many users likely have their PCs running for multiple days on end between restarts, and the chatter logs would be fairly unclear in that situation.
Thank you for the suggestion here, absolutely a good idea.

I've added it pretty much exactly as you described, via the commit above, and published it as [Release 1.09](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.09).

**Comment by Suddow** [comment]
Awesome, much appreciated!
