### ISSUE TITLE
Mouse with faulty scrolling

### ISSUE THREAD

**Issue by vacstr** [mcmonkeyprojects/KeyboardChatterBlocker#17]
On some of my mice with faulty scroll wheels (encoder), if I'm scrolling in a certain direction, it would spazz out where random inputs of the opposite direction would occur. Would be great if this program could block this kind of extremely fast direction switches in the scroll wheel (if that's even possible?).

**Comment by mcmonkey4eva** [comment]
This is slightly out-of-band for this project, as it's not quite a chatter problem. However it can be solved by the same software tools and handling methods, so I don't any reason to not add a solution for you.

Being so out of band, I haven't explicitly added an interface for it, but have instead made it be recognized as a fake 'key' named `wheel_change`. This 'key' is 'pressed' whenever the mouse wheel changes direction, so if it changes direction faster than the threshold configured for the key, it will block the direction change (and thus block any scrolling in the wrong direction until after the threshold passes).
To add it initially, you can manually add it in the config file (refer to the readme if you're unsure where that file is), with a line like `key.wheel_change: 200`. After it's added the first time, you can configure it from the same interface as you'd configure any other key's chatter limit.

This is added by the commit above and is available in [Release 1.10](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.10).
