### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by jackromen** [mcmonkeyprojects/KeyboardChatterBlocker#18]
I am not English Windows, when I open the program, the UI is different from your picture, the font is not the same, my font is wide, causing the interface to be misaligned, and cover the input box
I don't know how to send pictures, can you fix this ? I guess you if you let the program use Windows universal font, such as Arial may be FIX this problem.
The software is good, thank you again for your work.

**Comment by mcmonkey4eva** [comment]
I believe this should be prevented just by disabling Microsoft's automatic localization, however to be safe I've also manually forced a specific font to prevent any incorrect default font choice.

This fix is added by the commit above and is available in [Release 1.10](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.10).

If the new version still has that font issue, please reply to let me know. And also say which language your PC is configured to so I can try to replicate it.
