### ISSUE TITLE
Chatter is not detected or fixed when using Virtual Machine Connection (Hyper-V) on Windows 10

### ISSUE THREAD

**Issue by ezaum** [mcmonkeyprojects/KeyboardChatterBlocker#19]
When connecting to a VM running on Hyper-V on Windows through the Virtual Machine Connection the chatter is not detected and fixed.
Clicking away from the Virtual Machine Connection windows chatter is immediately detected and fixed.

**Comment by mcmonkey4eva** [comment]
I would imagine the logic that sends keystrokes through from your actual OS to the VM is operating on a much lower level than the simple userspace keyboard hook this program uses.

Theoretical solution A: completely rewrite the chatter blocker to operate on a lower system level (?)

Theoretical solution B: change the configuration of your VM software. I known for Oracle VM VirtualBox, there is an explicit option for whether to simply replicate keystrokes through or to claim direct hardware control & passthrough on input devices (the latter one having a special keycombo to disable the passthrough when needed).

Theoretical solution C: install chatter blocker on the VM (assuming the VM is running Windows)
