### ISSUE TITLE
Column sorting not working correctly

### ISSUE THREAD

**Issue by matbil82** [mcmonkeyprojects/KeyboardChatterBlocker#2]
When you sort the columns from low to high or high to low the program only seems to consider the first digit in the number. If you for example sort high to low it can look like this:

92
9
87
248

The problem is in count and chatter column under stats tab and in the chatter delay column under chatter log tab.

/Mats

**Comment by mcmonkey4eva** [comment]
Confirmed and replicated.
Seems to have been a simple mistake I made of converting the numeric values to strings, when they should have just been fed in as number.
Fixed and confirmed to be now correct, via the commit referenced above and released as 1.0.2 @ https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.0.2

Thank you for the report!
