### ISSUE TITLE
No context menu in taskbar

### ISSUE THREAD

**Issue by SebVFX** [mcmonkeyprojects/KeyboardChatterBlocker#20]
I can't open the context menu in taskbar. Only way to close it is through task manager. Don't know if it is a bug or intended but is a bit annoying.

- - -

Anyway. Thank you for the opportunity to suppress key chattering. That saved my day. Have a 2 years old coolermaster MK750 and the mx cherry brown switches began to chatter a lot. It works like a charm without any measurable cpu performance issues.

Thank you so very much!

**Comment by mcmonkey4eva** [comment]
Oh, sorry, I see how that'd be confusing. There isn't actually a context menu in the tray like many programs have - you're meant to just double-click the icon to open the interface, at which point you can uncheck "Enable" and close it.
Which is explained at the bottom of: https://github.com/mcmonkeyprojects/KeyboardChatterBlocker#setup

That said, now that you bring it up, yeah there should probably be a context menu in the tray with a force-close option.

**Comment by mcmonkey4eva** [comment]
Added a context menu to the tray icon by the commit above and available in [Release 1.11](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.11).
