### ISSUE TITLE
Small Interface Improvements

### ISSUE THREAD

**Issue by Flintpop** [mcmonkeyprojects/KeyboardChatterBlocker#21]
Small suggestion in the "**configure key**" tab of the program.

It could be great if **double clicking** inside the box and not only on the numbers would open the **editing values** tab.
Again, pressing **enter** should open the **editing tab** not skipping to the next line I think.
**Clicking** or (pressing enter)  on the letter could open **another editing tab** where we could edit the key.
When a key is selected and "**suppr**" is pressed it could be deleting it.

Thanks for this amazing app btw :) ! You may have prevented a unnecessary keyboard buy.

**Comment by mcmonkey4eva** [comment]
Added this in [Release 1.14](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.14).

- Clicking inside the box not just the text: yeah that was actually just a mistake on my part I think. It supports anywhere in the box now.
- Pressing enter while selected: hadn't really thought of keyboard interactions, but sure, added that.
- Editing the key: that is... sufficiently non-trivial that I'd rather not add that, and instead suggest if you need to edit a different key, just press the Add Key button.
- Delete: I'm not sure what `suppr` is, so I'm going to interpret that as the _Delete_ key.
