### ISSUE TITLE
Suggestion: Auto quit when anti-cheat software is open

### ISSUE THREAD

**Issue by Paulchief** [mcmonkeyprojects/KeyboardChatterBlocker#22]
I'd would be really useful if the software could automatically quit when it recognizes popular anti-cheat software (BattlEye, Easy Anti-Cheat, EQU8, ESEA, FacelT, mhyprot2, nProtect GameGuard, PunkBuster, Ricochet, TenProtect, Vanguard, XIGNCODE3,...)

It will just do a message pop-up with sound explaining why it's closing

**Comment by mcmonkey4eva** [comment]
This would require information and testing that I'm not able to do myself easily, but you (or another user reading this issue?) might be able to help provide.

---

**Question 1:** Does the program need to close entirely, or does simply deregistering all Windows API hooks suffice? Towards the end of testing that, I've tweaked the auto-disable-programs functionality*[1] to properly remove hooks when auto-disabling, and add them back only when re-enabled. In other words, if you add an anti-cheat program to the auto-disable-programs list, it should remove the hooks that said anti-cheat might be detecting.

*[1]: Tweak committed via the commit shown above, and in [Release 1.12](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.12)

I imagine this would suffice, but the only way I could think of verifying for sure, is, er, well... opening up some anti-cheat protected games with KeyboardChatterBlocker, making sure the anticheat is on the auto-disable list and that the blocker is indeed auto-disabled while the game is open, and then, uh, finding out whether or not you get banned or blocked. Certainly not a good idea to use any of your favorite games to test something like this! However, if you (or any reader) are willing and able to test this, it would be valuable to protect future users from mishaps.

---

**Question 2:** What are the precise program names of some likely to be relevant anti-cheat softwares? Specifically of the format that gets used in the Auto-Disable Programs list. You can find this even without KeyboardChatterBlocker open by running an anti-cheat protected game, then looking in task manager for the anticheat program - then, right click and select "go to details" to find the program name, it will look something like `some_anticheat.exe` (this name, minus the `.exe` suffix, is what KeyboardChatterBlocker checks against).

Assuming Question 1 works out and the deregistered hooks suffice, and we can get a good list of common anti cheat programs put together, I would be happy to include a default list of Auto-Disable-Programs that get added when the program is installed. If Question 1 doesn't work out, this list could be added by default to a separate feature of more aggressive auto-disable that fully closes the program as your initial idea was.
