### ISSUE TITLE
Suggestion: Program disabled by default, enables when it detects an application

### ISSUE THREAD

**Issue by MetalMinurz** [mcmonkeyprojects/KeyboardChatterBlocker#24]
A really neat addition to this project could be an ability to auto-enable the chatter blocker when it detects a certain program is running. For example, if I wanted to keep the chatter blocker disabled by default but have it enabled when on a specific chrome tab, the program could detect chrome is open, then see the tab name (chrome formats their tabs with something like: Google Chrome - "Tab name here"), and if the name includes a certain keyword such as maybe "essay" the program would enable. The program would then disable again if the tab changed or if chrome was closed.

Additionally, if the auto enable feature were to take precedence over auto-disable, that could add some additional benefits. For example, Minecraft is detected by the blocker as "javaw", but many other programs, such as Eclipse IDE use javaw. Having an ability to disable the logger when it detects javaw, but have it overwrite that when it detects Eclipse could potentially further its usability a lot IMO. There are just a few asuggestions I would find helpful to myself and most likely also would be useful to others.

**Comment by mcmonkey4eva** [comment]
You're describing a level of complexity in detection that I think honestly goes outside the scope of this project. For detecting _specific chrome tab names_ and having it disable or enable based on *a combination of multiple different programs affecting state preference*... you'd pretty much need a "custom detection script" or something for that - at which point it would make more sense to fork the repo and add your personal check requirements in C# to your fork.

You might also be interested in taking note of the addition for issue #26 - auto-disabling when there's a fullscreen application. Might help with your Minecraft case in particular, if you play minecraft in fullscreen.
