### ISSUE TITLE
Display version in the About tab

### ISSUE THREAD

**Issue by nemchik** [mcmonkeyprojects/KeyboardChatterBlocker#25]
I've just noticed the About tab doesn't indicate what version I'm running. The file properties shows `1.0.0.0` on the details tab. So I'm really not sure what version I'm running (probably the latest 🤷 )

![image](https://user-images.githubusercontent.com/725456/150859541-90717811-de0d-41ee-a190-ec9441fd1678.png)
![image](https://user-images.githubusercontent.com/725456/150859597-6fcc7bb7-61e1-4f66-8380-4ec3f1b0b6cf.png)

**Comment by mcmonkey4eva** [comment]
Added this in [Release 1.14](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.14).

The assembly version is now correct, and is also displayed on the about page.
