### ISSUE TITLE
Disable when using full screen application

### ISSUE THREAD

**Issue by tylerbarna** [mcmonkeyprojects/KeyboardChatterBlocker#26]
A toggle to disable the program when there's an application full screen would be nice since some games aren't listed in the dropdown menu

**Comment by mcmonkey4eva** [comment]
Added this in [Release 1.14](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.14).

There's a checkbox for `Auto Disable If Any Fullscreen` under the `Auto Disable Programs` list.
There's a corresponding config file entry as well of course.

It uses the Windows Shell Notification API to determine whether there's currently any fullscreen application, and as such may potentially fail to detect when Windows notification settings are altered, or an application does not run in "real" fullscreen (like "borderless window fullscreen").
