### ISSUE TITLE
Linux Version possibly?

### ISSUE THREAD

**Issue by DillFrescott** [mcmonkeyprojects/KeyboardChatterBlocker#27]
I love this program on Windows, but sadly my keyboard goes crazy on Linux without a chatter blocker.

**Comment by mcmonkey4eva** [comment]
It would have to be fundamentally different software on every level, from the internal keyboard interceptor code (which uses windows API calls directly) to even the GUI (which uses WinForms), so unfortunately no this can't really be made cross-platform.

**Comment by DillFrescott** [comment]
Okay
