### ISSUE TITLE
Prevent duplicate process instances

### ISSUE THREAD

**Issue by SevaOnOsu** [mcmonkeyprojects/KeyboardChatterBlocker#28]
I was testing the program in Minecraft parkour with 100ms threshold, and I was occasionally failing because of the random input delay. I was monitoring the chatter log while playing, and there was no chatter detected. I tested with 70ms and the delay was still happening. It doesn't always happen, which is the weird part. When I turned the threshold down to 50ms, the delay issues magically disappeared. I have no idea why this is happening.

**Comment by SevaOnOsu** [comment]
Update just tried playing with 50ms some more and the delay was all over the place and it was genuinely unplayable. The delay thing also happens in other games and even in browser

**Comment by SevaOnOsu** [comment]
Okay I think I found the issue. There were two instances of the program running, even though the 2nd one wasn't visible in tray or anywhere else, I had to kill it through task manager. You should probably make it so there can't be multiple instances of the program running at the same time.

**Comment by mcmonkey4eva** [comment]
Added for [(upcoming) release 1.15](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.15),

If there is a duplicate process launch, it will prevent the program from opening until you respond to a dialog box that lets you choose how to handle it (close other process, close this process, or allow the duplicate).
