### ISSUE TITLE
Volume scroll

### ISSUE THREAD

**Issue by m1k3r1** [mcmonkeyprojects/KeyboardChatterBlocker#29]
The program could be improved be being able to disable the effect on particular keys under Configure Keys, my volume scroll wheel works very very slowly when program is enabled
![image](https://user-images.githubusercontent.com/104593907/165830387-7e537ad8-5e59-4423-b660-eb2481addbfd.png)

**Comment by amparhizgar** [comment]
I think you can decrease the threshold to minimum (1 if possible) not 1000.
Same thing will happen.

**Comment by m1k3r1** [comment]
Yep, i set it to 0 and has effect of disabling, thanks
