### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by brynnb** [mcmonkeyprojects/KeyboardChatterBlocker#3]
Just wanted to say thanks! This is one of only two programs I can find that do this, the other is from 2014 and broke for me today. It was previously open source on sourceforge but I could no longer find the source to fix whatever problem it might have. Thankfully I found yours!

This has allowed me to use my Gigabyte Aero 15 without hating myself and the laptop. The chatter is very bad on certain keys. You've extended my patience with (and the lifetime of) this laptop considerably.

I dislike using issues for comments like this but didn't see any contact info for you.

**Comment by mcmonkey4eva** [comment]
❤️ 
This was a wonderful notification to wake up to. Really glad to hear this project helped you!
