### ISSUE TITLE
Add keyboard shortcut to disable. 

### ISSUE THREAD

**Issue by greenring** [mcmonkeyprojects/KeyboardChatterBlocker#30]
Excellent software!

It would be handy to have an instantaneous way to disable the app. E.g. by pressing some combo like ctrl+alt+f12 or something.

This will help macros and similar to dodge the chatter detection.

**Comment by KilliK69** [comment]
thank you. I was about to request the same thing, if possible to add a global hotkey to enable/disable the app. Unfortunately it  conflicts with my Autohotkey scripts, and I  have to manually enable/disable it  whenever I use them.

**Comment by mcmonkey4eva** [comment]
Added for [(upcoming) release 1.15](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.15),

This is initially implemented as requiring a direct config file edit (`config.txt`). You can add a line like: `hotkey_disable: control+alt+f12` while the program is closed, then open it, and it should work as intended.
