### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by SnowmanDK** [mcmonkeyprojects/KeyboardChatterBlocker#31]
I get an unhandled exception with the error message above when trying to activate "Start with Windows".
All other settings seem to work.
```
************** Exception Text **************
System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
   at IWshRuntimeLibrary.IWshShortcut.Save()
   at KeyboardChatterBlocker.MainBlockerForm.StartWithWindowsCheckbox_CheckedChanged(Object sender, EventArgs e) in C:\GitHub\mcmonkeyprojects\KeyboardChatterBlocker\KeyboardChatterBlocker\MainBlockerForm.cs:line 155
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by mcmonkey4eva** [comment]
That's... odd?

What that button do is essentially just, through a couple Win32 API calls, spawns a file into the folder path `%appdata%/Microsoft/Windows/Start Menu/Programs/Startup/` named `KeyboardChatterBlocker.lnk` as a link to the program's `.exe` to trigger it to run at startup.

That error message seems to imply that the `Startup` folder doesn't exist or somehow got deleted?

If you for some reason intentionally deleted that folder, well, er, go put it back lol?
If you didn't intentionally delete that, just open the path manually and create a folder with the same name - though you'll probably also want to investigate how it got deleted.

If that's not what happened, and the folder is there but the error still occurs, uh... well at that point I'd be at a loss, I can't think of any other reason that would happen.

**Comment by SnowmanDK** [comment]
I did check that the folder exists, and it does. I even manually created a shortcut to the program.
What it the exact line it adds to the settings file?... just so I can add it manually, so it shows a checkmark.

**Comment by mcmonkey4eva** [comment]
There is no settings entry, that checkbox is populated according to whether a file exists at that given path. If you add a shortcut manually to that path with the exact file name, the checkmark will enable itself automatically.

**Comment by 4rz0** [comment]
I'm having the same issue.
However, I also cannot navigate to the folder mentioned with the explorer, so your tool seems to be right with its error message.

What I do have is a folder `%programdata%\Microsoft\Windows\Start Menu\Programs\Startup`, which seems to be the startup for all users.
Might be an idea to use that instead.

**Comment by mcmonkey4eva** [comment]
Been a little while, but in release 1.15, there's now a check to create the folder if it doesn't exist automatically, which should prevent this issue in the future. Weird that it's not automatically generated for you though.

The programdata variant is for all-users rather than per individual user, and isn't a great option.
