### ISSUE TITLE
Suggestion: chatter notification sound

### ISSUE THREAD

**Issue by webmube** [mcmonkeyprojects/KeyboardChatterBlocker#32]
Would be really cool to be able to add a sound that notifies you whenever a chatter was detected and fixed.

**Comment by mcmonkey4eva** [comment]
Added for [(upcoming) release 1.15](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.15),

You can now place a `chatter.wav` file in the same folder as the `.exe` and it will automatically play when chatter is detected.
