### ISSUE TITLE
The Toggle Option does not work for me

### ISSUE THREAD

**Issue by BlackZero500** [mcmonkeyprojects/KeyboardChatterBlocker#38]
Hi there. I really love this tool because my Keyboard is driving me crazy. But as you know there are some problems while playing a game like i want to walk left, the character starts to walk left, stops (cause the key input gets deleted because of double input) and after a short pause starts again and walks left. So this is annoying of course. but i cant completely disable it because of the ingame Chat. So i thought the Toggle option would be perfect. But i cant get it to work. Right now i have the following line in the config:

hotkey_toggle: shift + alt + o

When i press this combo i hear a windows sound. but the Chatter Blocker does not get disabled or anything. it does nothing. Also when i try to use precise key names like you say in your readme like LShiftKey i get a message at start that i cant use more than one none modifier key. It will only recognize the Key if i type in shift. I tried many different combinations of keys but it wont work. can you help me?

**Comment by mcmonkey4eva** [comment]
You explicitly want `shift` and not `lshiftkey` for hotkey registration.

You can only use one non-modifier key.
This restrictions are from the Windows Hotkey API, not specific to KeyboardChatterBlocker. (That API is used so the program can entirely stop listening to keystrokes when not enabled, and thus make disabling it a safe way to avoid issues from anticheats and things like that).

If you hear a windows sound, it's likely that hotkey combo has already been registered by something else, and you just need a different key combo.
I encountered this a bunch in testing (thus why the readme says that `control` gets taken by other things really often, basically any combo with `control` in it was a conflict issue)
(Note: I strongly recommend avoiding keys that have chatter, or are configured for other options like the tempblock hotkey)

I'd suggest trying `win + shift + pause` and see if that works. If it does, then everything is functioning and you just need to pick a key combo that windows doesn't have other plans about.

**Comment by mcmonkey4eva** [comment]
It's... possible, but unlikely? At least there's no logical reason that _should_ be an issue. It goes through the windows hotkey API, so it's a classic case of... trusting Microsoft's code to figure it out.

It might be worth testing just to be safe - temporarily set the keyboard layout setting in windows to US-English QWERTY and see if key combos work?

It's possible that windows hotkeys have statically mapped some of the keys to where they are in QWERTY regardless of your layout? That'd be weird if so but it's possible.
