### ISSUE TITLE
Incorrect Sorting of "Chatter Delay (ms)" in "Chatter Log" Tab

### ISSUE THREAD

**Issue by karlkue** [mcmonkeyprojects/KeyboardChatterBlocker#39]
In the "Chatter Log" tab, when trying to sort the entries by "Chatter Delay (ms)", the sorting mechanism seems to be treating the values as strings instead of integers. This results in an incorrect sort order.

**Steps to Reproduce:**

1. Open "Keyboard Chatter Blocker".
2. Navigate to the "Chatter Log" tab.
3. Populate the log with multiple entries, ensuring that there are values with different numbers of digits (e.g., 104, 15, and 20).
4. Click on the "Chatter Delay (ms)" column header to sort the entries.

**Expected Result:**
The entries should be sorted in the following order (assuming an ascending sort): 15 -> 20 -> 104.

**Actual Result:**
The entries are sorted in the order: 104 -> 15 -> 20.

**Comment by mcmonkey4eva** [comment]
Ooh, yep, replicated. By mashing my keyboard fast enough to get a two digit time alongside 3 digit ones to test. Heh.
Fixed, and released as [release 1.17](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases)

**Comment by halt76** [comment]
1.16 is the latest.
where is 1.17 ?
