### ISSUE TITLE
ChatterBlocker Does Not Start With Windows

### ISSUE THREAD

**Issue by GlockFanBoy** [mcmonkeyprojects/KeyboardChatterBlocker#44]
Upon restart, ChatterBlocker does not start up despite being enabled as a task to launch during startup in Task Manager and the app itself.

**Comment by mcmonkey4eva** [comment]
To be clear: you understand it doesn't apply to the early parts of the OS start, ie login screen and all, and only applies once your user account is loaded, right? (I ask as this has been asked about before)

If it (A) is enabled, (B) has Start With Windows checked, and (C) shows as a launch process in TaskManager, I'm confused why it would be failing to start.

The way it works on the inside is actually dirt simple - it adds a shortcut to itself into the folder `%appdata%/Microsoft/Windows/Start Menu/Programs/Startup/`, which Windows automatically launches any shortcut it finds in that folder when it loads your user account.
I'm not aware, offhandedly at least, of any reason this wouldn't work.

Actually, one possible reason: did you reinstall or move your installation? if so the shortcut might point to the wrong location, in which case you can simply uncheck & recheck the starts with windows option to re-add it.
