### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by ron-azbel** [mcmonkeyprojects/KeyboardChatterBlocker#50]
Hey, been having some issues with some keys (t, y, backspace) on a laptop running Windows 11, it doesn't seem to be recognizing all chatters and it doesn't seem to work, am I doing something wrong?

![Screenshot 2024-05-28 214633](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/assets/119936620/3cfbd3dd-04ad-4db5-93ec-68a3e3c76315)
![Screenshot 2024-05-28 214614](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/assets/119936620/2222ab05-9bc0-4d29-b90a-681867ab49c2)

**Comment by mcmonkey4eva** [comment]
Your chatter times on the `T` key in that log seem to range up to almost 100ms in cases, so you'll want a threshold of 100 or higher for it to actually block that

**Comment by ron-azbel** [comment]
I've been trying different values for threshold, but it doesn't seem to
work, especially on backspaces
