### ISSUE TITLE
Possible to add mouse chatter fix?

### ISSUE THREAD

**Issue by appletechgeek** [mcmonkeyprojects/KeyboardChatterBlocker#51]
Heya good day. i have both a keyboard and a mouse  that both have chatter issues,

the software seems to work on my keyboard. my KB chatters at about 65~ MS,

but my mouse has significant chattering on the right click (typical logitech issue, have had it with 6 of their mice)

is it possible to add a chatter filter for mouse clicks too? i've been unable to find any program that fixes the mouse chatter clicks,

**Comment by mcmonkey4eva** [comment]
Mouse chatter filtering was added 4 years ago: https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/issues/8
Mouse wheel bouncing 3 years ago: https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/issues/17
Mouse buttons 4/5 (forward/backward) last year: https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/issues/36
