### ISSUE TITLE
Allow mouse buttons

### ISSUE THREAD

**Issue by TheRandomLabs** [mcmonkeyprojects/KeyboardChatterBlocker#8]
This would be useful for issues like [this](https://www.reddit.com/r/G502MasterRace/comments/6i94er/middle_mouse_button_double_click/), for example. Sorry if this isn't within the scope of this application!

**Comment by mcmonkey4eva** [comment]
That isn't in the scope of the application at all, and requires a lot of additional code to achieve.
But, well, ... I can't resist expanding scope for clearly useful new features, so... I've gone ahead and added it anyway, via the commits linked above and published as [Release 1.05](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.05).

Works pretty well at blocking chattering middle clicks. Works *too* well at blocking left clicks (I was reminded the hard way that it is in fact a normal everyday thing to intentionally 'chatter' the left mouse button ... which is called double-clicking... and is needed, for, y'know... removing a button from the block list...).

This was a fun adventure. Especially with how thoroughly _wrong_ all the documentation for Windows click interception is. Microsoft WindowsAPI Docs of all places should not be stating that things work ... inexplicably entirely differently than they do.

**Comment by TheRandomLabs** [comment]
Haha, thank you very much! You're a legend.
